### PR TITLE
Restart and shutdown; cosmetic fixes

### PR DESCRIPTION
**Pull request by hungrywolf27**

### CODE REVIEW

**Comment by hungrywolf27** [comment]
I'm working on updates for 0.11 and will have another pull request soon.

**Comment by icaruseffect** [comment]
Actually i would like to add you as maintainer. The PR were fine till now including a nice code cleanup and clean code additions.

**Comment by icaruseffect** [comment]
Or you could fork and take over. What do you prefer? :) 
I hope this is not too much, but i'm quite busy with other projects now.

**Comment by hungrywolf27** [comment]
Thanks! I think I'd prefer to be added as a collaborator rather than fork. That way, later on, if I don't have time to work on this but you do have time again, it might be easier.

After I commit the updates for 0.11, I'd like to make a posting about the update on the Syncthing forum, which hopefully will draw more users and contributors. OK?

**Comment by icaruseffect** [comment]
Deal. Welcome on board :)

**Pull request merged**
